name: webdriverio mobile Test
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20.
        - name: Install
          run: npm ci

       - name: Upload APK to BrowserStack
         uses: shreyanshp/upload-app-browserstack@v3
         with:
          app-path: browserstack_test/Android-NativeDemoApp-0.4.0.apk
          browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstack-accesskey: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          custom-id: "myApp"

        - name: Run test
          run: npm run wdio:xiaomi
          continue-on-error: true
      
        - name: Create report
          if: always()
          run: npm run allure:generate
        - name: Upload artifact allure-report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: allure-report
            path: ./allure-report

        - name: Publish test report
          uses: peaceiris/actions-gh-pages@v3
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-report