name: webdriverio mobile Test
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20.
        - name: Install
          run: npm ci

        - name: Upload apk file to browserstack
          run: |
            curl -u "${{secrets.BROWSERSTACK_USERNAME}}:${{secrets.BROWSERSTACK_ACCESS_KEY}}" \
            -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
            -F "file=@./Android-NativeDemoApp-0.4.0.apk" \
            -F "custom_id=myApp" \
            -F "ios_keychain_support=true"

        - name: Run test
          run: npm run wdio:xiaomi
          continue-on-error: true
      
        - name: Create report
          if: always()
          run: npm run allure:generate
        - name: Upload artifact allure-report
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: allure-report
            path: ./allure-report

        - name: Publish test report
          uses: peaceiris/actions-gh-pages@v3
          if: always()
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_branch: gh-pages
            publish_dir: allure-report